#include<stdio.h>
int main(){
char team[4][20];
int i,j,k,l[4],score[4][4],max=0,a,b[4],c[4];
    for(i=0;i<4;i++)
    {
        scanf("%s",team[i]);
    }
    for(i=0;i<4;i++)
    {
        for(j=0;j<4;j++)
        {
            scanf("%d",&score[i][j]);
        }
    }
    for(i=0;i<4;i++)
    {
        l[i]=0;
        for(j=0;j<4;j++)
        {
            k=score[i][j]-score[j][i];
            if(k>0)
                l[i]+=3;
            else if(k==0&&i!=j)
                l[i]+=1;
        }
    }
    for(i=0;i<4;i++)
    {
        b[i]=0;
        c[i]=0;
        for(j=0;j<4;j++)
        {
            k=score[i][j]-score[j][i];
            b[i]+=k;
            c[i]+=score[i][j];
        }
    }
    for(i=0;i<4;i++)
    {
        for(j=0;j<4;j++)
        {
        if(max<=l[j]&&l[j]!=-1)
            {
            max=l[j];
            a=j;
            for(k=0;k<4;k++)
                {
                if(k==j)
                    continue;
                if(l[k]==l[j])
                    {
                        if(b[k]>b[j])
                            a=k;
                        else if(b[k]==b[j])
                        {
                            if(c[k]>c[j])
                                a=k;
                        }
                    }
                }
            }
        }
        printf("%s %d\n",team[a],max);
        l[a]=-1;
        b[a]=-1;
        c[a]=-1;
        max=0;
    }
}
